name: Test

on:
  push:
    branches: [main]
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - '**.rst'
  pull_request:
    branches: [main]
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - '**.rst'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.9', '3.10']

    steps:
      - uses: actions/checkout@v2

      - name: Cache Setup
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install package
        run: |
          pip install -U pip setuptools wheel
          pip install .

      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 . --count --show-source --statistics

      - name: Lint with black
        run: |
          pip install black
          black --check .

      - name: Lint with isort
        run: |
          pip install isort
          isort -c yao

      # - name: Test with pytest
      #   run: |
      #     pip install pytest pytest-mock pytest-asyncio pytest-cov
      #     pytest

      # - name: Upload coverage to Codecov
      #   uses: codecov/codecov-action@v3
      #   with:
      #     file: ./coverage.xml
